/**
 * FOUNDER "WHAT'S LEFT" — single source of truth for /admin/settings.
 *
 * WORKING RULE: whenever something is left undone — an unset secret, an idea
 * not built yet, a manual step waiting on an account — ADD IT HERE so it shows
 * up in the admin Settings panel. This is the founder's live to-do surface.
 * Keep it honest: move items to status "done" (or delete) when they ship.
 */

/* ── Integrations / secrets the app looks for ──────────────────────────────
 * The Settings page checks process.env for each `envVars` entry (server-side,
 * values are NEVER exposed — only whether they are set). */
export type IntegrationCategory =
  | "Core" | "Payments" | "AI" | "Email & alerts" | "Growth & ads" | "Add-on providers";

export interface Integration {
  label: string;
  envVars: string[]; // all must be set to count as configured
  category: IntegrationCategory;
  required: boolean; // required = the app is degraded without it
  note?: string;
}

export const INTEGRATIONS: Integration[] = [
  // Core
  { label: "Supabase URL", envVars: ["NEXT_PUBLIC_SUPABASE_URL"], category: "Core", required: true },
  { label: "Supabase service key", envVars: ["SUPABASE_SERVICE_ROLE_KEY"], category: "Core", required: true, note: "server-side DB" },
  { label: "Admin password", envVars: ["ADMIN_PASSWORD"], category: "Core", required: true },
  { label: "Admin JWT secret", envVars: ["ADMIN_JWT_SECRET"], category: "Core", required: true, note: "signs your session (32+ chars). Since 2026-07-27 production FAILS CLOSED without it" },
  { label: "Admin 2FA (TOTP)", envVars: ["ADMIN_TOTP_SECRET"], category: "Core", required: false, note: "optional but recommended: GET /api/admin/2fa-setup while logged in, add the secret to your authenticator app + Vercel, redeploy. Login then requires password + 6-digit code" },
  { label: "GitHub client-site archive", envVars: ["GITHUB_ARCHIVE_TOKEN", "GITHUB_ARCHIVE_REPO"], category: "Core", required: false, note: "create a PRIVATE repo (e.g. AmraniHub/servolia-client-archive) + a fine-grained PAT with Contents read/write on it. Every published site auto-snapshots there; restore via /api/admin/archive-site" },
  // Payments
  { label: "Stripe secret key", envVars: ["STRIPE_SECRET_KEY"], category: "Payments", required: true, note: "checkout, Care, add-ons" },
  { label: "Stripe webhook secret", envVars: ["STRIPE_WEBHOOK_SECRET"], category: "Payments", required: true, note: "confirms payments + provisions add-ons" },
  // AI
  { label: "Anthropic API key", envVars: ["ANTHROPIC_API_KEY"], category: "AI", required: true, note: "client receptionists + copy generation" },
  { label: "Cloudflare AI (fallback)", envVars: ["CLOUDFLARE_ACCOUNT_ID", "CLOUDFLARE_AI_TOKEN"], category: "AI", required: false, note: "Llama fallback when Claude is down" },
  // Email & alerts
  { label: "Resend (transactional email)", envVars: ["RESEND_API_KEY"], category: "Email & alerts", required: true },
  { label: "Email from-address", envVars: ["EMAIL_FROM"], category: "Email & alerts", required: false },
  { label: "Telegram bot token", envVars: ["TELEGRAM_BOT_TOKEN"], category: "Email & alerts", required: false, note: "instant lead + add-on alerts" },
  { label: "Telegram chat id", envVars: ["TELEGRAM_CHAT_ID"], category: "Email & alerts", required: false },
  // Growth & ads
  { label: "Meta pixel id", envVars: ["NEXT_PUBLIC_META_PIXEL_ID"], category: "Growth & ads", required: false },
  { label: "Meta Conversions API token", envVars: ["META_CAPI_ACCESS_TOKEN"], category: "Growth & ads", required: false, note: "server-side ad conversion tracking" },
  { label: "GA4 service account", envVars: ["GOOGLE_SERVICE_ACCOUNT_KEY"], category: "Growth & ads", required: false, note: "Daily Stats + Weekly SEO" },
  { label: "GA4 property id", envVars: ["GA4_PROPERTY_ID"], category: "Growth & ads", required: false },
  { label: "Google Ads conversion id", envVars: ["NEXT_PUBLIC_GOOGLE_ADS_ID"], category: "Growth & ads", required: false, note: "AW-XXXXXXXXXX from Google Ads → Tools → Conversions. Fires site-wide alongside GA4; link GA4 key events in the Google Ads UI to import them as conversions" },
  { label: "Google Places API (prospect import)", envVars: ["GOOGLE_PLACES_API_KEY"], category: "Growth & ads", required: false, note: "powers the Google Maps button on /admin/prospects — ~$0.035 per search (per click, returns up to 20 businesses), first ~1,000 searches/mo free. Enable 'Places API (New)' in Google Cloud Console" },
  { label: "LinkedIn (auto-post to Company Page)", envVars: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET", "LINKEDIN_ACCESS_TOKEN", "LINKEDIN_ORGANIZATION_URN"], category: "Growth & ads", required: false, note: "content engine drafts → approve → auto-posts. Token expires ~60 days, see roadmap" },
  // Add-on providers (the reseller layer — mostly NOT set yet)
  { label: "Twilio (SMS add-on)", envVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"], category: "Add-on providers", required: false, note: "auto-provisions the SMS reminders add-on" },
  { label: "Cloudflare Registrar (domain add-on)", envVars: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"], category: "Add-on providers", required: false, note: "auto-registers client domains" },
  { label: "Google Workspace reseller (email add-on)", envVars: ["GOOGLE_WORKSPACE_RESELLER_TOKEN"], category: "Add-on providers", required: false, note: "needs Google partner approval first" },
];

/* ── Roadmap: what's left to build / decide / set up ───────────────────── */
export type RoadmapStatus = "todo" | "in_progress" | "blocked" | "done";

export interface RoadmapItem {
  title: string;
  detail?: string;
  status: RoadmapStatus;
  priority: 1 | 2 | 3; // 1 = do now
  needs?: string;      // account/secret/decision it waits on
}

export const ROADMAP: RoadmapItem[] = [
  { title: "Confirm the conversation-meter is compérage-safe (French lawyer)", priority: 1, status: "blocked", needs: "the same French lawyer review already queued for pay-per-booking", detail: "The 2026-07-28 pricing model meters INCLUDED AI CONVERSATIONS per month (100/300/800) rather than bookings. The reasoning: charging per patient booked is a fee tied to patient volume, which compérage restricts for regulated professions — but metering conversations is metering a technical resource, ordinary SaaS, so it should be fine for dental too. That reasoning is sound but UNCONFIRMED. Get it in writing before leaning on it in public copy or a sales call. If a lawyer disagrees, the fallback is flat tiers with no meter (just feature tiers), which costs the expansion-revenue property but nothing else." },
  { title: "Update the CGV for the new pricing model", priority: 1, status: "done", detail: "SHIPPED 2026-07-28: both /legal/cgv and /fr/legal/cgv now import SETUP_PLAN + PLANS and describe the €490 installation paid in full up front, the monthly subscription, annual at ten months for twelve, and 30 days' cancellation notice. The 50/50 deposit mechanic is gone from the contract, the refund policies (EN + FR) match, and §5 Revisions now says ONE round included with the installation — the earlier draft invented per-tier revision counts that contradicted the scope document." },
  { title: "Finish the pricing sweep across marketing + transactional surfaces", priority: 1, status: "done", detail: "SHIPPED 2026-07-28, after an adversarial audit found the first pass had only covered files that grepped for the word 'Care'. Fixed since: /api/checkout charged 50% (€245) of the installation and wrote balance_due — now charges in full with balance_due 0; the post-payment email said 'your €245 deposit cleared' and promised a 'final payment' — rewritten as installationPaidEmail; the chat prompt hardcoded '50% deposit' two lines under the interpolated price block; buildProgress had a 'Balance paid' step that could never complete, which parked every delivered build on waiting-on-client forever and kept the guarantee pause engaged; the Stripe webhook's recovery path booked total_price as amountPaid × 2. Marketing: both homepages, ROICalculator, Guarantee, the niche + dental + aesthetic funnels, the 45 FR geo pages and country pages, /fr/solutions tags, both case-study pages, both contact dropdowns (which were writing retired plan names into plan_interest and mis-scoring every lead), pages.ts, portalDict + the portal upsell ladder (now driven by subscription tier, not build plan), systemGuide." },
  { title: "Zero-Miss Guarantee — decide, then write it into the CGV", priority: 2, status: "done", detail: "SHIPPED 2026-07-28. 'Every enquiry answered within 60 seconds, 24/7 — or that month is free.' Written into both CGV as section 4 bis and both refund policies as 2 bis, with real exclusions (client-side DNS/hosting, non-payment suspension, client config changes, announced maintenance, upstream AI outage persisting past the fallback). Remedy is capped at that month's plan fee, measured on server-side timestamps the client can check in their portal. Guarantee.tsx now leads with it. OPERATIONAL DEPENDENCY: this is a real refund liability that assumes the receptionist keeps answering — it holds only while the Claude→Llama fallback chain is funded and healthy. Top up Anthropic credits before pushing this hard in outbound." },
  { title: "Watch the Zero-Miss guarantee automatically", priority: 2, status: "todo", needs: "a cron over chat_sessions", detail: "The guarantee is live in the contract but nothing measures it yet. Needed: a job that scans chat_sessions per client per month for any visitor message whose first assistant reply is >60s later, flags the month, and either auto-credits or alerts the founder. Until this exists the promise is honoured on request only — which is legally fine but means a miss could go unnoticed and unrefunded, which is exactly the failure that kills trust in a guarantee." },
  { title: "Dental template does not render opening hours", priority: 2, status: "todo", needs: "a go-linda decision on the dental template", detail: "Found 2026-07-28 by running the new audit engine against our own /sites/demo-metay: it scored 7.0 and lost the trust dimension because no opening hours are rendered (address and postcode are). Patients check hours constantly, and the audit engine we now ship to prospects scores every clinic on exactly this. Fix belongs in the dental niche template + practicalInfo defaults — gated behind 'go linda', so not touched." },  { title: "TOP UP ANTHROPIC API CREDITS — every AI feature is silently degraded", priority: 1, status: "blocked", needs: "console.anthropic.com → Plans & Billing", detail: "Diagnosed 2026-07-27 from the failing blog-generator workflow: the production ANTHROPIC_API_KEY returns 'credit balance is too low'. Impact right now: blog + LinkedIn generation fail, client-site copy generation falls back to the mechanical draft (no AI copy), Solia falls back to Cloudflare Llama, cold-email drafting falls back to the static template, client-report narratives skip, Linda copilot down. Everything self-heals the moment credits are added — no code change needed." },
  { title: "Switch Stripe to LIVE keys", priority: 1, status: "blocked", needs: "sk_live_… in Vercel", detail: "Production is on test keys — nothing charges real money until live keys are set." },
  { title: "Land the first real clients", priority: 1, status: "in_progress", detail: "The whole machine exists (demo → generate → publish → monthly plan + add-ons). Outbound to the dental-France beachhead; country pages catch SEO inbound." },
  { title: "Create the custom_requests + email_campaigns + client_profiles tables in Supabase", priority: 1, status: "done", detail: "custom_requests powers personalized extra work + its payment link; email_campaigns records broadcast history; client_profiles stores the client's photo, name, phone and marketing opt-in. Ran 2026-07-25." },
  { title: "Create the page_views table in Supabase", priority: 1, status: "done", detail: "Powers /admin/traffic (servolia.com visitors) AND the portal's Visitors tab (each client's own site traffic). Ran 2026-07-25." },
  { title: "Set ANALYTICS_SALT in Vercel", priority: 2, status: "todo", needs: "any long random string", detail: "Salts the daily visitor hash in /api/track. Without it a default is used, which still works but is guessable — set a real secret before treating visitor counts as private data." },
  { title: "Meta Pixel + Google Ads tag — decision made: keep both", priority: 3, status: "done", detail: "Resolved 2026-07-25: the RETIRED thing is the paid-ads-as-a-service OFFERING sold to clients (Ads Landing plan, pricing.ts) — not Servolia's own client-acquisition tracking. The founder runs Google Ads + Meta Ads to bring in Servolia's own clients, so both stay: Meta Pixel (Analytics.tsx, unchanged) + a new Google Ads conversion tag (NEXT_PUBLIC_GOOGLE_ADS_ID, same file). /legal/terms already discloses the pixel correctly — no change needed there." },
  { title: "Google Ads conversion tag live", priority: 3, status: "done", detail: "AW-9742210978 (from customer id 974-221-0978) hardcoded as the default in src/components/Analytics.tsx, same pattern as the GA4/Pixel defaults — fires site-wide (never on /sites/*) alongside GA4. Next: link GA4 key events (e.g. Purchase) in the Google Ads UI to pull them in as conversions — no code needed for that step, it's a Google Ads UI setting." },
  { title: "Collect real client reviews before showing any testimonials", priority: 2, status: "blocked", needs: "a first delivered client", detail: "The reviews section is deliberately NOT built with invented quotes or stock faces — fake social proof is the fastest way to lose credibility in a small referral-driven niche. Ask the first real client for a quote + photo, then it ships in EN and FR." },
  { title: "Complete Stripe account verification (KYC)", priority: 1, status: "blocked", needs: "business details + ID in the Stripe dashboard", detail: "Separate from live keys: Stripe must verify YOU before it will pay out to your bank. Money can be collected but not withdrawn until this clears." },
  { title: "send.servolia.com in Resend — deferred until real broadcast volume", priority: 3, status: "blocked", needs: "Resend Pro ($20/mo) — only worth it past ~50 outbound sends/mo or when broadcasts start", detail: "Decision 2026-07-27: servolia.com is verified and sending on the free plan (1 domain slot). The isolated send. subdomain was reputation insurance for BULK email; current volume is transactional + a few founder-led cold emails/day, which doesn't justify $20/mo. Revisit when broadcasts actually launch — then upgrade, add send.servolia.com, and point the broadcast sender at it." },
  { title: "French version of /onboarding (paid-client intake)", priority: 1, status: "done", detail: "Shipped as /fr/demarrage. Buyers coming from /fr/tarifs get a French Stripe checkout and land on the French intake; the portal links FR clients there too. Both pages are noindex (post-payment)." },
  { title: "Client emails in the recipient's language", priority: 2, status: "done", detail: "Completed 2026-07-27: every client-facing template in src/lib/email.ts is now EN+FR — deposit-received and call-booking already were; added FR to audit confirmation (lang from the form's language field), portal magic-link (login page sends its UI language), portal-message notification (language read from the client's own site config via build_id), and the go-live email. NOTE the go-live email (liveEmail) is written but not wired to any route — sending it when a build flips to live is still manual." },
  { title: "French version of /call (book a discovery call)", priority: 2, status: "done", detail: "Shipped 2026-07-27 as /fr/appel — BookingWidget already spoke French (lang prop), so this wraps it in the FR nav/footer with hreflang + sitemap. Point French demo sites and ads at /fr/appel." },
  { title: "French legal pages: privacy, CGV, refund", priority: 2, status: "done", detail: "Shipped 2026-07-27: /fr/legal/confidentialite, /fr/legal/cgv (NOTE: the old /legal/cgv page had a CGV *title* but English *content* — the /fr/ version is the first actual French legal text on the site), /fr/legal/remboursement. All hreflang-paired with the EN pages, linked from the FR footer, in the sitemap. Still English-only: /legal/terms (site usage terms — lowest legal priority since CGV governs sales)." },
  { title: "French versions of /solutions/[slug] and /niches/*", priority: 3, status: "in_progress", detail: "10 SEO/funnel pages with no French equivalent — pure missed organic reach in the beachhead market. FIRST TRANCHE SHIPPED 2026-07-27: /fr/[niche]/[ville] (dentiste, clinique-esthetique, services-a-domicile × 15 top FR cities = 45 geo pages) + /fr/villes hub. Uses FAQPage + LocalBusiness/Service JSON-LD so LLMs (Perplexity, Google AI Overviews, ChatGPT) can lift the answers. SECOND TRANCHE SHIPPED 2026-07-27: /fr/esthetique — the dedicated aesthetic funnel matching /fr/dentistes depth, leading with the pay-per-booking offer (the only niche allowed to see it); linked from the FR footer + homepage industry grid. THIRD TRANCHE SHIPPED 2026-07-27: all 6 data-driven marketing pages translated — /fr/solutions/{sites-ia, receptionniste-ia, reservation-en-ligne, crm-tableaux-de-bord} + /fr/secteurs/{experts-comptables, consultants} (French slugs, hreflang-paired via enPath, MarketingPage grew a lang prop, FR solutions hub cards now deep-link). The EN /niches/* funnel pages (dentists, aesthetic-clinics, home-services) already have FR equivalents (/fr/dentistes, /fr/esthetique, geo pages) — this item is now DONE for every page that matters." },
  { title: "French blog (/blog + /blog/[slug])", priority: 3, status: "blocked", needs: "Anthropic credits topped up FIRST (generation is down), then a session to extend the content engine", detail: "Deliberately deferred 2026-07-27 during the optimization batch: the blog generator currently fails with 'credit balance too low', so extending a pipeline that can't run would be untestable half-work. Once credits are in and EN generation is verified green again, the FR extension is: FR keyword clusters in blogClusters.ts, a lang field on blog_posts, the generator alternating EN/FR runs, and /fr/blog routes. Lowest-urgency FR surface — the geo pages + funnels carry French SEO for now." },
  { title: "Connect Twilio → SMS add-on auto-provisions", priority: 2, status: "todo", needs: "TWILIO_ACCOUNT_SID + TWILIO_AUTH_TOKEN" },
  { title: "Open Cloudflare Registrar → domain add-on automatic", priority: 2, status: "todo", needs: "CLOUDFLARE_API_TOKEN (+ account id)" },
  { title: "Pay-per-booking — code complete; run the SQL block to switch it on", priority: 1, status: "blocked", needs: "run the pay-per-booking SQL block at the end of supabase/schema.sql (+ live Stripe keys)", detail: "CODE SHIPPED 2026-07-27: (1) /api/checkout-ppb charges the €990 setup in full (card saved for off-session billing) — POST returns {url}, or send the GET link directly: servolia.com/api/checkout-ppb?niche=aesthetic&lang=fr. Server-side payPerBookingEligible() gate refuses dental/medical no matter what the link says. (2) The Stripe webhook's ppb_setup branch creates the build + an active clients row with billing_mode per_booking and the rate snapshot. (3) /api/cron/monthly-invoice runs the 1st at 09:00 (vercel.json): tallies unbilled qualified bookings per client, writes one pay_per_booking_invoices ledger row per period (unique constraint = re-runs can't double-charge), stamps chat_sessions.billed_at, creates+sends the real Stripe invoice (7 days to pay), Telegram summary. ATTENDANCE is manual-by-exception: void/adjust no-shows in the Stripe dashboard within the 7-day window — the Telegram ping is the review prompt. Dental/medical stays blocked behind the French lawyer sign-off on compérage (unchanged)." },
  { title: "Google Workspace reseller → email add-on automatic", priority: 3, status: "todo", needs: "Google partner approval + GOOGLE_WORKSPACE_RESELLER_TOKEN" },
  { title: "B2B financing partner for builds", priority: 3, status: "todo", detail: "€0 upfront / €X/mo — financier pays us today, client pays them monthly." },
  { title: "White-label / multi-tenant for other agencies", priority: 3, status: "todo", detail: "Sell the platform to everyone who sells to clinics — the picks-and-shovels play." },
  { title: "GDPR DPA per client", priority: 3, status: "todo", detail: "We now process patient data across clinics — needs a data-processing agreement." },
  { title: "Retired /niches/lawyers to match the P2 exclusion list", priority: 3, status: "done", detail: "Same treatment as real-estate (2026-07-25): removed the 'lawyers' entry from the industries array in src/lib/content/pages.ts (this also auto-removes it from the sitemap and the /solutions page nav, since both derive from that array), dropped the Footer link and the 2 law-firm blog clusters, and added a permanent redirect /niches/lawyers → /contact. Law-firm prospects still self-identify via forms/chat, same as real-estate." },
  { title: "LinkedIn Company Page auto-posting", priority: 3, status: "done", detail: "LINKEDIN_CLIENT_ID/SECRET/ACCESS_TOKEN/ORGANIZATION_URN set in Vercel (2026-07-23). Content engine drafts a post → approve via Telegram or /admin/content → postLinkedInDraft() publishes to the Servolia Company Page automatically." },
  { title: "Redo the LinkedIn OAuth connect flow", priority: 2, status: "todo", needs: "recurring, every ~60 days", detail: "LinkedIn access tokens on the Development Tier expire in ~60 days and can't be refreshed silently — visit /api/admin/linkedin-oauth/start again, then paste the new LINKEDIN_ACCESS_TOKEN into Vercel. Until this is redone periodically, auto-posting silently falls back to 'copy the text and post manually' (see postLinkedInDraft in src/lib/contentActions.ts)." },
  { title: "Enable Stripe events invoice.payment_failed + invoice.paid on the webhook", priority: 1, status: "todo", needs: "Stripe dashboard → Developers → Webhooks", detail: "Powers the payment-failed banner in the client portal, the shut-off on /sites/[slug], and the past-due badge in /admin/clients. Also add the new columns via the SQL block at the bottom of supabase/schema.sql (payment_status, past_due_since, suspend_at, suspended_at, last_payment_failure_reason, open_invoice_url). Grace window is 14 days — see GRACE_DAYS in /api/webhooks/stripe/route.ts." },
  { title: "Extend /admin/data-room into the exit brochure (Priestley)", priority: 3, status: "todo", detail: "A data room ALREADY EXISTS at /admin/data-room (diligence-ready export center with consent-basis documentation) — do NOT build a second one. When 6+ paying clients exist, EXTEND it with the three Priestley brochure pieces: (1) 5-year financial forecast from clients MRR + growth, (2) asset register (sites, content, integrations, SOPs), (3) key-clients page (top clients by lifetime value). Until then the existing export center is enough." },
  { title: "Google Places prospect import — code shipped, needs the API key", priority: 2, status: "blocked", needs: "GOOGLE_PLACES_API_KEY (Google Cloud Console → enable 'Places API (New)')", detail: "SHIPPED 2026-07-27: the Google Maps button on /admin/prospects takes a plain search ('clinique esthétique Lyon') and imports up to 20 businesses with phone, website, city and Google rating via the Places Text Search API — duplicates skipped by business name. ~$0.035/search, first ~1,000/mo free. Until the key is set the endpoint returns a clear 503. Flow: Google Maps import → mystery-shop the best-rated → Generate demo → Email." },
  { title: "Per-prospect custom domain for cold-outreach demos", priority: 3, status: "todo", needs: "Cloudflare Registrar API token + a Vercel domain-add API path", detail: "Right now the outbound preview URL is servolia.com/sites/{slug}. Servolia.com is already a branded custom domain (Vercel is invisible on the wire), but the /sites/ path signals 'template on someone else's platform' — which hurts cold-open rates. Better: register a short throwaway domain per prospect (e.g. metay-lyon-demo.com) via Cloudflare Registrar, attach it to Vercel via the API, and rewrite to /sites/{slug} internally. ~$10/domain amortised across expected 3-week outbound window. Build only when outbound volume justifies the per-prospect cost (>50 sends/mo)." },
  { title: "Plan promises delivered: lead alerts, portal pipeline, Sheets sync, GDPR pages — run the pipeline SQL", priority: 1, status: "in_progress", needs: "run the client-lead-pipeline SQL block in supabase/schema.sql (chat_sessions.client_status/client_note)", detail: "Shipped 2026-07-27 after a promise-vs-delivery audit of the pricing pages. (1) INSTANT LEAD ALERTS (€590 'Lead capture + email notification'): every captured lead — booking form or chat, transition-only so conversations can't spam — emails the clinic owner instantly, bilingual, with the after-hours '🌙 caught while you were closed' framing (the unique retention moment), a one-tap wa.me reply to the lead's phone with prefilled text (delivers the €990 'WhatsApp lead notification' — true API-sent WhatsApp needs Twilio, future), tel:/mailto buttons and a portal link. src/lib/clientNotify.ts. (2) PORTAL LEAD PIPELINE (€990 'Lead pipeline with statuses' + 'Client notes & history'): status per lead (new→contacted→booked→won/lost) + a private note, PATCH scoped to the client's own sites. (3) GOOGLE SHEETS SYNC (€590 promise): set config.sheetsWebhookUrl on a site and every lead POSTs a JSON row to the client's Apps Script sheet. (4) GDPR PAGE (every plan's 'GDPR pages included'): /sites/{slug}/confidentialite auto-populated from config, bilingual, linked in every client-site footer." },
  { title: "Delivery pipeline: plan templates + GitHub archive — create the archive repo + PAT", priority: 2, status: "blocked", needs: "a private GitHub repo + GITHUB_ARCHIVE_TOKEN/GITHUB_ARCHIVE_REPO in Vercel", detail: "Shipped 2026-07-27: (1) PLAN TEMPLATES — planFeatures() in clientSites.ts maps each pricing tier to the feature set the generated site ships with: Website System (€290) gets site + booking form but NO AI receptionist; Booking/Client/pay-per-booking get everything. The widget is hidden AND /api/chat refuses the slug server-side (no free inference). Demos always get the full product (the pitch). Existing rows default all-on. (2) GITHUB ARCHIVE — publishing a site auto-commits sites/{slug}.json to the archive repo (siteArchive.ts, Contents API, updates in place so git history = version history); POST /api/admin/archive-site {slug,restore:true} pulls a snapshot back as a DRAFT. Until the token/repo are set, publishes just log 'archive skipped' — nothing breaks." },
  { title: "Security hardening + admin 2FA shipped — enable 2FA + run the rate_limits SQL", priority: 1, status: "in_progress", needs: "run the security SQL block in supabase/schema.sql (rate_limits table); then enable 2FA via /api/admin/2fa-setup + ADMIN_TOTP_SECRET in Vercel", detail: "Shipped 2026-07-27: (1) JWT secret now FAILS CLOSED in production — the old fallback was a public string in the repo, i.e. forgeable admin sessions if the env var was ever unset. (2) Admin login: constant-time password compare, cross-instance rate limit 8/15min per IP, optional TOTP 2FA (RFC 6238, zero dependencies — /api/admin/2fa-setup generates the secret, login page has the code field, wrong-password and wrong-code are indistinguishable). (3) Security headers site-wide: HSTS, nosniff, X-Frame-Options, Referrer-Policy, Permissions-Policy. (4) Portal: magic-link requests limited 5/15min per IP AND 3/15min per target email (anti email-bombing, silently — same response shape); password login upgraded from per-lambda memory throttle to the shared DB-backed limiter. Until the rate_limits SQL runs, limiting gracefully degrades to per-instance memory. FUTURE (not now): CSP header — needs a nonce pipeline because of GA/Meta inline scripts; revisit when traffic justifies it." },
  { title: "Retired webapp + mobile plans; deleted diag crons; pruned excluded-niche residue", priority: 3, status: "done", detail: "2026-07-27 full-system audit outcome: generic Web App / SaaS and Mobile App offers diluted the clinic-niche monopoly positioning — marked retired:true in pricing.ts (old builds still render their names) and removed their sections + FAQs from /pricing and /fr/tarifs. Deleted diag-latest-build + diag-trigger-cancel debug cron routes. Pruned real-estate / lawyers / law-firm / wealth-management / luxury-real-estate values from estimateLeadValue (supabase.ts), scoring.ts, valueEquation.ts, pollinations.ts, and the generator prompt — excluded niches now fall through to defaults. Dental funnel kept (deepest asset, still a served niche, just not the ad spearhead)." },
];

export const STATUS_META: Record<RoadmapStatus, { label: string; color: string; bg: string }> = {
  todo:        { label: "To do",       color: "#92400E", bg: "#FEF3C7" },
  in_progress: { label: "In progress", color: "#1D4ED8", bg: "#DBEAFE" },
  blocked:     { label: "Blocked",     color: "#B91C1C", bg: "#FEE2E2" },
  done:        { label: "Done",        color: "#166534", bg: "#DCFCE7" },
};
