/**
 * WHAT HAPPENS TO THE OTHER LANGUAGE WHEN A CLIENT REWRITES A LINE.
 *
 * goodscochina.com serves Arabic from a dictionary keyed on the ENGLISH text:
 * js/i18n.js walks the page's text nodes and swaps any string it recognises.
 * That design needs no markup, which is why it was used on a page generated by
 * a dead CMS — but it means the translation is bound to the exact wording.
 *
 * So the moment she edits an English line, that line stops being recognised
 * and an Arabic visitor sees English there. Nothing errors, nothing logs, and
 * the person least likely to notice is the owner, who reads the English site.
 *
 * TWO THINGS WE DELIBERATELY DO NOT DO.
 *
 * We do not move the dictionary entry onto her new wording. Keeping the old
 * Arabic against new English means an Arabic visitor is told something the
 * business no longer says, and nobody can see it. Falling back to English is
 * visibly imperfect; a stale translation is invisibly wrong.
 *
 * We do not block the save. She asked for control of her own pages and she
 * has it. She is told, in her own words, which lines now read in English on
 * the Arabic version, so it is her decision and not a surprise.
 */

/**
 * The English strings this dictionary can translate.
 *
 * Parsed with a regex rather than by executing the file: this is a client's
 * repository, the content is fetched over the network, and running it to read
 * it would be running someone else's JavaScript on our server. A key we fail
 * to parse only costs a warning the client did not need.
 *
 * Handles the two shapes the file actually uses — a key and value on one line,
 * and a key whose value is wrapped onto the next.
 */
export function translatedStrings(source: string): Set<string> {
  const keys = new Set<string>();
  // "English text": followed by a string literal, possibly after a newline.
  const re = /"((?:[^"\\]|\\.)*)"\s*:\s*\n?\s*"(?:[^"\\]|\\.)*"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    const key = m[1].replace(/\\(.)/g, "$1").trim();
    if (key) keys.add(key);
  }
  return keys;
}

/**
 * Of the lines just saved, the ones the other language cannot render.
 *
 * Compared on the same normalisation the dictionary lookup uses — collapsed
 * whitespace — because a line she retyped with two spaces is the same line to
 * a reader and a different one to an exact-match table.
 */
export function untranslatedAfterEdit(
  source: string,
  savedValues: string[],
): string[] {
  const norm = (s: string) => s.replace(/\s+/g, " ").trim();
  const known = new Set([...translatedStrings(source)].map(norm));
  return savedValues.filter((v) => v.trim() && !known.has(norm(v)));
}

/**
 * What she is told, in her words. Returns null when there is nothing to say —
 * an empty warning shown every time is a warning nobody reads.
 */
export function translationNote(count: number, language: string): string | null {
  if (count < 1) return null;
  return count === 1
    ? `One line you changed has no ${language} version yet, so ${language} visitors will see it in English. Tell us and we will translate it.`
    : `${count} lines you changed have no ${language} version yet, so ${language} visitors will see them in English. Tell us and we will translate them.`;
}
